CREATE TABLE UAT_DM.AR_Goodok_subs_march AS (
SELECT DISTINCT SUBS_ID, EXTRACT(DAY FROM VALID_FROM_DATE) cl_day, EXTRACT(month FROM VALID_FROM_DATE) cl_month, EXTRACT(YEAR FROM VALID_FROM_DATE) cl_year FROM PRD2_DDS_V.SERVICE_INSTANCE
WHERE CREATION_DTTM BETWEEN DATE'2018-03-01' AND DATE'2018-03-31'
AND SERVICE_ID = 214
AND SERVICE_STATUS_ID = 1
) WITH NO DATA;

INSERT INTO UAT_DM.AR_Goodok_subs_march
SELECT DISTINCT SUBS_ID, EXTRACT(DAY FROM VALID_FROM_DATE) cl_day, EXTRACT(month FROM VALID_FROM_DATE) cl_month, EXTRACT(YEAR FROM VALID_FROM_DATE) cl_year FROM PRD2_DDS_V.SERVICE_INSTANCE
WHERE CREATION_DTTM BETWEEN DATE'2018-03-01' AND DATE'2018-03-31'
AND SERVICE_ID = 214
AND SERVICE_STATUS_ID = 1